pool:
  vmImage: 'vs2017-win2016'

strategy:
  matrix:
    desktop:
      target_platform: 'desktop'
      target_generator: 'Visual Studio 15 2017 Win64'
  maxParallel: 1

steps:
- script: |
    dir
    choco install python -y -o -ia "'/qn /norestart ALLUSERS=1 TARGETDIR=D:\Python37'"
    dir
    choco install -y patch
    choco install -y curl
    pip install -U vcstool
    D:\Python37\python.exe -m pip install -U setuptools pip
    pip install -U colcon-common-extensions
    pip install -U catkin_pkg EmPy git+https://github.com/lark-parser/lark.git@0.7d pyparsing pyyaml
    pip install -U pytest coverage mock
    pip install -U flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes pep8 pydocstyle
    choco install -y cppcheck
    md \dev\ros2\src
    cd \dev\ros2
    curl -sk https://github.com/DynoRobotics/unity_ros2/raw/master/ros2_unity_win10_standalone.repos -o unity_ros2.repos
    vcs import src < ros2_unity.repos
    dir
    D:\Python37\Scripts\colcon.exe
  displayName: 'Build with colcon'
