pool:
  vmImage: 'vs2017-win2016'

strategy:
  matrix:
    desktop:
      target_platform: 'desktop'
      target_generator: 'Visual Studio 15 2017 Win64'
  maxParallel: 1

steps:
- script: |
    pip install vcstool
    pip install -U catkin_pkg EmPy pyparsing pyyaml colcon-common-extensions setuptools pytest coverage mock
    pip install -U catkin_pkg EmPy git+https://github.com/lark-parser/lark.git@0.7d pyparsing pyyaml
    pip install -U flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes pep8 pydocstyle
  displayName: 'Install dependencies'

- script: |
    set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin
    md \dev\ros2\src
    cd \dev\ros2
    curl -sk https://github.com/DynoRobotics/unity_ros2/raw/master/ros2_unity_win10_standalone.repos -o unity_ros2.repos
    vcs import src < ros2_unity.repos
    C:\Python37\Scripts\colcon.exe build
    call install\local_setup.bat
  displayName: 'Build with colcon'
