version: 2.1

jobs:
  build:
    docker:
      - image: dynorobotics/ros2_dotnet:crystal
    steps:
      - run: mkdir -p ros2_unity_ws/src
      - run: wget https://github.com/DynoRobotics/unity_ros2/raw/master/ros2_unity_standalone.repos
      - run: vcs import ros2_unity_ws/src < ros2_unity_standalone.repos
      - run: cd ros2_unity_ws && colcon build
