version: 2.1

jobs:
  build:
    docker:
      - image: dynorobotics/ros2_mono:latest
    steps:
      - run: mkdir -p ros2_dotnet_ws/src
      - run: wget https://github.com/DynoRobotics/unity_ros2/raw/master/ros2_unity.repos
      - run: vcs import ros2_dotnet_ws/src < ros2_unity.repos
      - run: source /opt/ros/crystal/setup.bash && cd ros2_dotnet_ws && colcon build
